=== xixiwu-design/HTML/XML/RA4_XSD_Final/Ej5.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dades">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nom" maxOccurs="3" type="xs:string"></xs:element>
                                        <xs:element name="cognoms">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="primer"></xs:element>
                                                    <xs:element name="segon" minOccurs="0"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="complet">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="si"></xs:enumeration>
                                                            <xs:enumeration value="no"></xs:enumeration>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                
                                            </xs:complexType>
                                        </xs:element>
                                         <xs:element name="dni" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="tipus" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                           
                            <xs:element name="direccio">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="tipus" type="xs:string"></xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="comentari" type="xs:string" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== xixiwu-design/HTML/XML/RA4_XSD_Final/Ej5_personal.xml
<?xml version="1.0" encoding="UTF-8"?>
<personal
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Ej5.xsd">
    <persona id="p01">
        <dades tipus="personals">
            <nom>Eduard</nom>
            <cognoms complet="si">
                <primer>Moliner</primer>
                <segon>Luque</segon>
            </cognoms>
            <dni>25390952J</dni>
        </dades>
        <direccio tipus="A">Padilla 34 1-2</direccio>
        <comentari>Dades alumnat</comentari>
    </persona>
    <persona id="p02">
        <dades tipus="oficials">
            <nom>Josep</nom>
            <nom>Manel</nom>
            <cognoms complet="no">
                <primer>Vera</primer>
            </cognoms>
            <dni>45390952H</dni>
        </dades>
        <direccio tipus="A">Pearson 34 1-2</direccio>
        <comentari>Això és una persona oficial</comentari>
    </persona>
</personal>
