=== xixiwu-design/HTML/XML/RA4_Final/Ej1.dtd
<!ELEMENT llibreria (llibre+)>
<!ATTLIST llibre id ID #REQUIRED>
<!ELEMENT llibre  (titol,autor,genere,preu)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT genere (#PCDATA)>
<!ELEMENT preu (#PCDATA)>
<!ATTLIST preu moneda (EUR | DOL) "EUR">

=== xixiwu-design/HTML/XML/RA4_Final/Ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llibreria SYSTEM "Ej1.dtd">
<llibreria> 
  <llibre id="L001"> 
    <titol>1984</titol> 
    <autor>George Orwell</autor> 
    <genere>Ficció</genere>     
    <preu moneda="DOL">12.99</preu> 
  </llibre> 
  <llibre id="L002"> 
    <titol>Orgull i prejudici</titol> 
    <autor>Jane Austen</autor> 
    <genere>Romàntic</genere>     
    <preu moneda="DOL">10.50</preu> 
  </llibre> 
</llibreria>
