=== xixiwu-design/HTML/XML/RA4_Final/Ej5.dtd
<!ELEMENT inventari (vehicle+)>
<!ELEMENT vehicle (dades,ubicacio,comentari)>
<!ATTLIST vehicle id ID #REQUIRED>

<!ELEMENT dades (marca,model,matricula)>
<!ATTLIST dades tipus (comercial|personal) #REQUIRED>

<!ELEMENT ubicacio (#PCDATA)>
<!ATTLIST ubicacio tipus CDATA #REQUIRED>

<!ELEMENT comentari (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT model (nom,variant?)>
<!ATTLIST model complet (si|no) "si">

<!ELEMENT matricula (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT variant (#PCDATA)>

=== xixiwu-design/HTML/XML/RA4_Final/EJ5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventari SYSTEM "Ej5.dtd">
<inventari> 
    <vehicle id="v01"> 
        <dades tipus="comercial"> 
            <marca>Toyota</marca> 
            <model complet="si"> 
                <nom>Hilux</nom> 
                <variant>GR-Sport</variant> 
            </model> 
            <matricula>1234ABC</matricula> 
        </dades> 
        <ubicacio tipus="garatge">Zona A, plaça 15</ubicacio> 
        <comentari>Vehicle de càrrega lleugera</comentari> 
    </vehicle> 
    <vehicle id="v02"> 
        <dades tipus="personal"> 
            <marca>BMW</marca> 
            <model complet="no"> 
                <nom>Serie 3</nom> 
            </model> 
            <matricula>5678DEF</matricula> 
        </dades> 
        <ubicacio tipus="exterior">Pàrquing B, plaça 22</ubicacio> 
        <comentari>Vehicle assignat a direcció</comentari> 
    </vehicle> 
</inventari>
