=== xixiwu-design/HTML/XML/RA4_Final/Ej7.dtd
<!ELEMENT productes (producto+)>
<!ELEMENT producto (nom,descripcio?,categoria?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>

<!ATTLIST producto codi ID #REQUIRED>
<!ATTLIST producto preu CDATA #REQUIRED>
<!ATTLIST producto disponibilitat CDATA "disponible">

=== xixiwu-design/HTML/XML/RA4_Final/Ej7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productes SYSTEM "Ej7.dtd">
<productes>
    <producto codi="P001" preu="1.99" disponibilitat="disponible">
        <nom>llet</nom>
        <descripcio>Llet dolça</descripcio>
        <categoria>Begudes</categoria>
    </producto>
    <producto codi="P002" preu="19.99" disponibilitat="disponible">
        <nom>xocolata</nom>
        <categoria>xocolata</categoria>
    </producto>
    <producto codi="P003" preu="0.99" disponibilitat="no disponible">
        <nom>Pa</nom>
        <descripcio>Al·lèrgens: Cereals</descripcio>
    </producto>
</productes>
