=== xixiwu-design/HTML/XML/RA4/XSD/ej1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="registrealumnes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumne" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom" type="xs:string"/>
                            <xs:element name="cognom" type="xs:string"/>
                            <xs:element name="edat" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== xixiwu-design/HTML/XML/RA4/XSD/ej1.xml
<?xml version="1.0" encoding="UTF-8"?>

<registrealumnes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ej1.xsd">
    <alumne>
        <nom>Anna</nom>
        <cognom>García</cognom>
        <edat>22</edat>
    </alumne>
    <alumne>
        <nom>Joan</nom>
        <cognom>Pérez</cognom>
        <edat>19</edat>
    </alumne>
</registrealumnes>
